Implement Observer to DriverManager
iis-powp-2023-mbgc2backup/powp_jobs2d_projects pull request #3
Opened 2023-04-18 11:45 UTC by mario0000o7

2023-04-18 12:05 UTC, kowallus commented
Please resolve conflicts

2023-04-19 07:11 UTC, kowallus requested changes
Poor approach to git.
Please fix listed issues.

2023-04-19 07:11 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +    private CommandManager commandManager;
Refactor (renaming) could be in the separate PR and it sure shouldn't be in the same commit with adding an Observer. 
Please revert renaming.

2023-04-19 07:11 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DriverFeature.java
> +public class DriverFeature implements Subscriber {
Do not add new responsibilities to DriverFeature. Please implement a separate Subscriber class.

2023-05-08 17:36 UTC, tobiasz135 commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +    private CommandManager commandManager;
Name has been already changed by someone else.

2023-05-08 17:37 UTC, tobiasz135 reviewed
Task has been fixed

2023-05-09 07:02 UTC, kowallus requested changes
Fix name of the observer class

2023-05-09 07:02 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/events/DriverFeatureSubscriber.java
> +public class DriverFeatureSubscriber implements Subscriber {
All subscribers of DriverManager can be considered DriverFeatureSubscriber.
The name of the subscribe should indicate what is done upon notification (update method logic).

2023-05-09 07:02 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> -        DriverFeature.updateDriverInfo();
I am not sure if the correct name of a driver appears on startup now. Please verify.

2023-05-09 08:24 UTC, tobiasz135 commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> -        DriverFeature.updateDriverInfo();
The name appears correctly.

2023-05-09 08:42 UTC, tobiasz135 commented on src/main/java/edu/kis/powp/jobs2d/events/DriverFeatureSubscriber.java
> +public class DriverFeatureSubscriber implements Subscriber {
Name updated

2023-05-09 08:43 UTC, tobiasz135 reviewed
Task issues have been fixed.

2023-05-09 08:50 UTC, kowallus approved these changes
OK

2023-05-09 08:54 UTC, merged