Added importing commands from text
iis-powp-2023-mbgc2backup/powp_jobs2d_projects pull request #30
Opened 2023-05-13 18:22 UTC by Ewangelina

2023-05-15 13:33 UTC, kowallus requested changes
The idea is correct however please clean the code and get rid of the reflection (or provide in a more clear and independent way)

2023-05-15 13:33 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +        }
This is not a clean code. It is hard to grasp why you use reflection here. It would be better to use pure OO solutions

2023-05-15 13:33 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +                return null;
throw exception

2023-05-15 13:33 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +    public boolean acceptText(String input)
what is the purpose of this method? Wrong name? Maybe javadoc would be necessary.

2023-05-15 13:33 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +        return false;
maybe it should be abstract?

2023-05-15 13:33 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFromJson.java
> +    CommandFromJson()
Why not public?

2023-05-15 13:33 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFromJson.java
> +    public boolean acceptText(String input)
maybe parseText would be better?

2023-05-15 13:33 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +        }
Try more SRP. Extract this static method to a separate class.

2023-05-15 13:33 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +    protected static DriverCommand createCommand(String command, Integer x, Integer y)
name 'command' is not precise

2023-05-15 17:26 UTC, Ewangelina commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFromJson.java
> +    CommandFromJson()
It is public

2023-05-17 14:35 UTC, Ewangelina commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +        return false;
It is now abstract.

2023-05-17 20:21 UTC, kowallus approved these changes
Could be a little bit better, but it is mergeable ;)

2023-05-17 20:21 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +        return null;
null's should be avoided (exception? empty command?)

2023-05-17 20:21 UTC, kowallus commented on src/test/java/edu/kis/powp/resources/Example json command.json
examples are in a wrong folder. Regularly maven projects use folders src/test/resources or src/main/resources

2023-05-17 20:21 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandFactory.java
> +    public static CommandImporter interpretInput(String input)
It would be better to provide an interface for CommandFactory (with non-static CommandImporter). Then the instance could be injected into CommandManagerWindow (without introducing indirect dependencies to GUI classes).

2023-05-17 20:21 UTC, merged