(IO3) MACRO - recording driver calls as commands
iis-powp-2023-mbgc2backup/powp_jobs2d_projects pull request #35
Opened 2023-05-17 17:43 UTC by patrykbajos

2023-05-17 20:46 UTC, kowallus requested changes
not complete and not quite convincing

2023-05-17 20:46 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/decorator/ContextCommand.java
> +            visitor.visit((OperateToCommand) command);
I do not understand the idea of 'ContextCommand' clearly, but this line could be easily replaced by:
command.accept(visitor)

2023-05-17 20:46 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/decorator/ContextCommand.java
> +    private final Job2dDriver executor;
"recording" the driver used would make sense if it could be used explicitly, e.g., as an option for changing the current driver. 
According to the DriverCommand interface "executor" is not part of the command but is rather specified in the execution time (it is a param of execute).

2023-05-17 20:46 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/SelectRunCurrentCommandOptionListener.java
> +        command.execute(null);
Passing null is ugly and incomprehensible. It probably also brakes existing features. Moreover, something doesn't make sense because RecordingDriver is never used (maybe you forgot to commit changes to TestJobs2dApp?

2023-05-18 11:31 UTC, patrykbajos commented
Funkcjonalność po konsultacji została porzucona i nowa wersja jest na gałęzi `feature/macro-v3` w naszym repozytorium.

2023-05-18 11:31 UTC, closed without merging