Add history of commands window
iis-powp-2023-mbgc2backup/powp_jobs2d_projects pull request #39
Opened 2023-05-23 09:47 UTC by tobiasz135

2023-05-24 12:35 UTC, kowallus requested changes
Please apply OBJECT-oriented approach, not STATIC-class-approach. Minimize static fields and methods. We try to learn using objects.

2023-05-24 12:35 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/HistoryOfUsedCommandsSubscriber.java
> +    HistoryOfUsedCommandsWindow historyOfUsedCommandsWindow;
should be private

2023-06-06 08:54 UTC, tobiasz135 reviewed
Task issues fixed

2023-06-06 09:20 UTC, kowallus approved these changes

2023-06-06 09:21 UTC, kowallus approved these changes

2023-06-06 09:21 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/HistoryOfUsedCommandsManager.java
> +
interesting formatting

2023-06-06 09:21 UTC, merged